import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Token Portal</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
      </Head>

      <main className={styles.main}>
        <h2>My Token</h2>
        <div className={styles.card}>
          <div>Balance</div>
        </div>
        <div className={styles.card}>
          <div>Total Supply</div>
        </div>
        <div className={styles.card}>
          <div>Mint</div>
          <div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
